FROM node:22-alpine AS builder

WORKDIR /app

ARG SANITY_PROJECT_ID=lxmhb5oh
ARG SANITY_DATASET=production
ARG SANITY_API_VERSION=2025-01-01
ARG SANITY_READ_TOKEN=
ARG SANITY_WRITE_TOKEN=

COPY package*.json ./
RUN npm ci

COPY . .
RUN SANITY_PROJECT_ID=$SANITY_PROJECT_ID \
    SANITY_DATASET=$SANITY_DATASET \
    SANITY_API_VERSION=$SANITY_API_VERSION \
    SANITY_READ_TOKEN=$SANITY_READ_TOKEN \
    SANITY_WRITE_TOKEN=$SANITY_WRITE_TOKEN \
    npm run build

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 80

ENV HOST=0.0.0.0
ENV PORT=80

CMD ["node", "./dist/server/entry.mjs"]
