server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/[^.?]*[^/]$ {
        return 308 https://$host$uri/$is_args$args;
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
