const destination = {
  name: "destination",
  type: "document",
  title: "Destination",
  fields: [
    {
      name: "title",
      type: "string",
      title: "Title",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    },
    {
      name: "summary",
      type: "text",
      title: "Summary",
      rows: 3,
    },
    {
      name: "body",
      type: "array",
      title: "Body",
      of: [
        {
          type: "block",
          styles: [
            { title: "Paragraph", value: "normal" },
            { title: "Paragraph - Justified", value: "bodyJustify" },
            { title: "Paragraph - Left", value: "bodyLeft" },
            { title: "Paragraph - Center", value: "bodyCenter" },
            { title: "Paragraph - Right", value: "bodyRight" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Quote", value: "blockquote" },
          ],
        },
        {
          type: "object",
          name: "quickVerdict",
          title: "Quick Verdict",
          fields: [
            { name: "eyebrow", type: "string", title: "Eyebrow" },
            { name: "title", type: "string", title: "Title", validation: (Rule) => Rule.required() },
            { name: "body", type: "text", title: "Body", rows: 4, validation: (Rule) => Rule.required() },
          ],
          preview: {
            select: {
              title: "title",
              subtitle: "eyebrow",
            },
          },
        },
        {
          type: "object",
          name: "highlightBox",
          title: "Highlight Box",
          fields: [
            {
              name: "tone",
              type: "string",
              title: "Tone",
              initialValue: "tip",
              options: {
                list: [
                  { title: "Tip", value: "tip" },
                  { title: "Important", value: "important" },
                  { title: "Budget Note", value: "budget" },
                  { title: "Route Note", value: "route" },
                ],
                layout: "radio",
              },
            },
            { name: "title", type: "string", title: "Title" },
            { name: "body", type: "text", title: "Body", rows: 4, validation: (Rule) => Rule.required() },
          ],
          preview: {
            select: {
              title: "title",
              subtitle: "tone",
              body: "body",
            },
            prepare({ title, subtitle, body }) {
              return {
                title: title || "Highlight Box",
                subtitle: subtitle || body,
              };
            },
          },
        },
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            { name: "alt", type: "string", title: "Alt text" },
            { name: "caption", type: "string", title: "Caption" },
          ],
        },
      ],
      description: "Full editorial content for this destination",
    },
    {
      name: "image",
      type: "image",
      title: "Image",
      options: { hotspot: true },
      fields: [
        { name: "alt", type: "string", title: "Alt text" },
        { name: "caption", type: "string", title: "Caption" },
      ],
    },
    {
      name: "gallery",
      type: "array",
      title: "Gallery",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            { name: "alt", type: "string", title: "Alt text" },
            { name: "caption", type: "string", title: "Caption" },
          ],
        },
      ],
      description: "Optional secondary images for this destination.",
    },
    {
      name: "workflowStatus",
      type: "string",
      title: "Workflow status",
      initialValue: "image_pending",
      options: {
        list: [
          { title: "Image Pending", value: "image_pending" },
          { title: "Review Ready", value: "review_ready" },
          { title: "Published", value: "published" },
        ],
        layout: "radio",
      },
      description: "Editorial workflow state for AI-generated or manually drafted content.",
    },
    {
      name: "generatedBy",
      type: "string",
      title: "Generated by",
      description: "Optional note for the model or workflow that created the draft.",
    },
    {
      name: "generatedAt",
      type: "datetime",
      title: "Generated at",
      description: "When this draft was generated by the editorial pipeline.",
    },
    {
      name: "imageAltSuggestion",
      type: "string",
      title: "Image alt suggestion",
      description: "Suggested alt text to copy into the image field after uploading the final visual.",
    },
    {
      name: "region",
      type: "string",
      title: "Region",
      description: "Project-specific: Swiss region label",
    },
    {
      name: "bestSeason",
      type: "string",
      title: "Best season",
      description: "Project-specific: e.g. spring, summer, winter",
    },
  ],
};

export default destination;
